//! 更新默认主题配置后，需要执行 npm run build:theme 重新构建index.json

import fs from 'node:fs'
import path from 'node:path'

import { createThemeColors } from './utils.js'

const defaultThemes = [
  {
    id: 'midnight',
    name: '深夜留声 / Midnight',
    isDark: true,
    config: {
      primary: 'rgb(30, 215, 96)',
      font: 'rgb(250, 250, 250)',
      '--color-app-background': '#000000',
      '--color-main-background': '#000000',
      '--color-content-background': '#121212',
      '--color-surface-raised': '#242424',
      '--color-scheme': 'dark',
      '--color-progress-track': '#4d4d4d',
      '--color-progress-fill': '#f5f5f5',
      '--color-font': '#f5f5f5',
      '--color-font-label': '#b3b3b3',
      '--color-font-error': '#ff8c97',
      '--color-font-warning': '#f0c15c',
      '--color-primary-font': '#f5f5f5',
      '--color-primary-font-hover': '#ffffff',
      '--color-primary-font-active': '#1ed760',
      '--color-primary-background': '#292929',
      '--color-primary-background-hover': '#252525',
      '--color-primary-background-selected': '#333333',
      '--color-primary-background-active': '#303030',
      '--color-button-font': '#e6e6e6',
      '--color-button-font-selected': '#1ed760',
      '--color-button-background': '#272727',
      '--color-button-background-selected': '#383838',
      '--color-button-background-hover': '#363636',
      '--color-button-background-active': '#444444',
      '--color-border': '#ffffff1a',
      '--color-accent-on': '#07190d',
      '--color-play-button': '#ffffff',
      '--color-play-button-on': '#111111',
      '--color-playlist-hero': '#503997',
      '--color-playlist-hero-end': '#2c214f',
      '--color-home-tint': '#213b30',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--background-blur': '0',
      '--color-btn-hide': '#353535',
      '--color-btn-min': '#353535',
      '--color-btn-close': '#cf354d',
      '--color-badge-primary': '#a7cdb4',
      '--color-badge-secondary': '#bcb3d9',
      '--color-badge-tertiary': '#d6ba8c',
    },
  },
  {
    id: 'grey',
    name: '灰常美丽 / Light',
    isDark: false,
    config: {
      primary: 'rgb(108, 122, 137)',
      font: 'rgb(33, 33, 33)',
      '--color-app-background': '#e9ecef',
      '--color-main-background': '#e9ecef',
      '--color-content-background': '#ffffff',
      '--color-surface-raised': '#f0f2f4',
      '--color-scheme': 'light',
      '--color-font': '#212121',
      '--color-font-label': '#59636e',
      '--color-font-error': '#b3273e',
      '--color-font-warning': '#795300',
      '--color-primary-font': '#3f4a56',
      '--color-primary-font-hover': '#212121',
      '--color-primary-font-active': '#3f4a56',
      '--color-primary-background': '#edf0f2',
      '--color-primary-background-hover': '#e6eaee',
      '--color-primary-background-selected': '#dce2e7',
      '--color-primary-background-active': '#dce2e7',
      '--color-button-font': '#34404c',
      '--color-button-font-selected': '#212121',
      '--color-button-background': '#edf0f2',
      '--color-button-background-selected': '#d5dce3',
      '--color-button-background-hover': '#dfe5ea',
      '--color-button-background-active': '#d2dae1',
      '--color-border': '#0000001a',
      '--color-accent-on': '#ffffff',
      '--color-play-button': '#212121',
      '--color-play-button-on': '#ffffff',
      '--color-progress-track': '#c6cdd4',
      '--color-progress-fill': '#465563',
      '--color-playlist-hero': '#d8d5e8',
      '--color-playlist-hero-end': '#ebe9f3',
      '--color-home-tint': '#e8edf0',
      '--color-switch-track': '#8b949d',
      '--background-image': 'none',
      '--background-image-position': 'center',
      '--background-image-size': 'cover',
      '--background-blur': '0',
      '--color-btn-hide': '#68737e',
      '--color-btn-min': '#68737e',
      '--color-btn-close': '#b3273e',
      '--color-badge-primary': '#526170',
      '--color-badge-secondary': '#726572',
      '--color-badge-tertiary': '#776346',
    },
  },
]

const themes = defaultThemes.map(({ config: { primary, font, ...extInfo }, ...themeInfo }) => ({
  ...themeInfo,
  isCustom: false,
  config: {
    themeColors: createThemeColors(primary, font, themeInfo.isDark),
    extInfo,
  },
}))

fs.writeFileSync(path.join(import.meta.dirname, 'index.json'), JSON.stringify(themes, null, 2))
